{% set version = "1.1.0" %}

package:
  name: demoji
  version: {{ version }}

source:
  # pypi does not include tests
  url: https://github.com/bsolomon1124/demoji/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 0cde672b31ce04917d4001607406f0d6bbe91942873d780316dc296723e914af

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - demoji = demoji.main:main

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7

test:
  source_files:
    - tests
  requires:
    - pip
    - coverage
    - pytest
  imports:
    - demoji
  commands:
    - pip check
    - demoji --help
    - coverage run --source=demoji --branch -m pytest -vv --tb=long --color=yes
    - coverage report --show-missing --skip-covered --fail-under=64

about:
  home: https://github.com/bsolomon1124/demoji
  summary: Accurately remove and replace emojis in text strings
  dev_url: https://github.com/bsolomon1124/demoji
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
